ManageIQ/activerecord-virtual_attributes

- .travis.yml
- spec/db/models.rb
- spec/db/schema.rb
- spec/support/database.rb
- spec/support/have_virtual_column.rb
- spec/support/with_test_class.rb
- spec/virtual_attributes_spec.rb
- spec/virtual_total_spec.rb
- virtual_attributes.gemspec
trying to get bundler and rails to work
> travis build

- CHANGELOG.md
- README.md
- lib/active_record/virtual_attributes/version.rb
> Add changelog entries for 1.0.0

- .codeclimate.yml
- .rubocop.yml
- .rubocop_cc.yml
- .travis.yml
- README.md
- activerecord-virtual_attributes.gemspec
- spec/spec_helper.rb
Prepare initial third party services
> Prepare initial third party services

- lib/active_record/virtual_attributes/virtual_fields.rb
These are code formatting only to fix code climate errors
> code climate tweaks

- lib/active_record/virtual_attributes/rspec/have_virtual_attribute.rb
alias a matcher instead of duplicating the code
> code climate - remove duplicate matcher

- Gemfile
- spec/virtual_attributes_spec.rb
> Fix sporadic test failures

- .codeclimate.yml
- .yamllint
- lib/active_record/virtual_attributes.rb
- lib/active_record/virtual_attributes/virtual_arel.rb
- lib/active_record/virtual_attributes/virtual_delegates.rb
> Fix some trivial cops

- lib/active_record/virtual_attributes/virtual_fields.rb
make code climate happy
not impressed with this extraction but...
> extract replace_virtual_field_hash

- Gemfile
- gemfiles/virtual_attributes_50.gemfile
- gemfiles/virtual_attributes_51.gemfile
- gemfiles/virtual_attributes_52.gemfile
it is a nitpick from rubocop, but simple to fix so, what ever
> change order of gemfile to make cops happy

- lib/active_record/virtual_attributes/virtual_fields.rb
don't modify the fields parameter passed into select()
as a rule of thumb, not modifying parameters is a pretty basic statement.
This was causing some problems with MIQ, but I wasn't able to create a reproducer
> don't munge select fields

- CHANGELOG.md
- lib/active_record/virtual_attributes/version.rb
thinking this is a minor version since it only updates bugs.
> 1.4.0 version notes

- spec/virtual_includes_spec.rb
we will refactoring the way preload works.
So we want specs in place.
We already had specs for `includes()` and `includes().references()`.
This PR adds `preload` specs.
> specs for preloaded

- spec/db/models.rb
- spec/db/schema.rb
- spec/virtual_includes_spec.rb
1. simplify definitions of `has_many` (no need to declare `class_name`)
2. define and test habtm
> test has many

- lib/active_record/virtual_attributes/virtual_total.rb
Creating the aggregate attribute arel has 2 paths: one for `size` and one for all others.
So there is no need to pass in a `method=size` and then later change the value to `count`.
Instead, passing in `method=count` and remove the `if` check.
The column itself is simpler. If it is an arel friendly column,
leave it as arel (checking `respond_to?(:count)`), otherwise convert
to an arel attribute
> No longer hard code size method in arel generation

- lib/active_record/virtual_attributes/virtual_total.rb
This is pulled out of #15 
When attempting to come up with an agreement between #13 and #15 there are some common changes made.
These are the changes from that PR (well both to be honest) that do not change any results.
> virtual_total refactorings

- spec/db/models.rb
- spec/virtual_total_spec.rb
> fix virtual spelling mistake

- CHANGELOG.md
- lib/active_record/virtual_attributes/version.rb
we may want to merge 2 PRs before releasing version 1.5:
> v1.5 notes

- lib/active_record/virtual_attributes/virtual_arel.rb
- spec/db/models.rb
- spec/db/schema.rb
- spec/support/database.rb
- spec/support/preload_values.rb
- spec/support/query_counter.rb
- spec/support/with_test_class.rb
- spec/virtual_attributes_spec.rb
- spec/virtual_delegates_spec.rb
- spec/virtual_total_spec.rb
most of these are in specs and are trivial
fixing anyway
left 3 lambdas alone since those lines are being changed in another PR
> fix cops for lambda, %i %w and spacing

- lib/active_record/virtual_attributes/virtual_fields.rb
> fix spelling of debugging

- CHANGELOG.md
- README.md
- lib/active_record/virtual_attributes/version.rb
> 1.6 changelog

- CHANGELOG.md
- lib/active_record/virtual_attributes/version.rb
releasing a more friendly 2.0 version
> v2.0 changes

- CHANGELOG.md
- lib/active_record/virtual_attributes/version.rb
we said in https://github.com/ManageIQ/activerecord-virtual_attributes/pull/15 that we were updating the major version
@kbrock do you want the changelog in this PR or can I make you do it for me?
> update to 3.0.0

- README.md
mostly removing unneeded commas and a plurality issue
> minor grammar fixes on the description

- .codeclimate.yml
- .rubocop.yml
- .rubocop_cc.yml
- activerecord-virtual_attributes.gemspec
change to the right manageiq style url
> fix the rubocop style urls for codeclimate

- Gemfile
future changes are v6 centric
setting that as the default
we are still testing against the v5 versions
> v6 default gemfile

- README.md
Hakiri is no longer supported
Dependabot runs on github and provides a similar service
> drop hakiri

- CHANGELOG.md
- lib/active_record/virtual_attributes/version.rb
updates for the next version.
This version is mostly for rails6.1 functionality
> v6 release notes

- CHANGELOG.md
- lib/active_record/virtual_attributes/version.rb
* fix HomogeneousIn clauses #111
> release 6.1.1

- spec/virtual_delegates_spec.rb
extracted from #114 
mostly focused on ensuring the arel coming from the delegate works correctly.
I thought we had the grouping and to_sql in VirtualDelegate#select_from_alias
was to ensure that binding variables did not get botched,
but I can't reproduce the issue and get it to fail.
Adding these specs for now and hoping to get a good reproducer for the need
of the `Arel.sql(arel.to_sql)`
> spec: ensure delegates work with OR and HomogeneousIn

- .github/workflows/ci.yaml
> Add Ruby 3.0 to CI

- activerecord-virtual_attributes.gemspec
the build suite depends upon these gems.
Adding them
> add missing developer dependencies

- bin/console
- spec/support/database.rb
Configure `bin/console` so you can use it to test and verify virtual attributes
> fix bin/console

- lib/active_record/virtual_attributes/virtual_total.rb
> Use Arel.sql shortcut for sql literals

- lib/active_record/virtual_attributes/virtual_arel.rb
I was so excited to get this fix into 7.1
> Document that in 7.1, this monkey patch is no longer needed

- spec/virtual_attributes_spec.rb
> Order specs

- spec/virtual_attributes_spec.rb
> minor specs

- activerecord-virtual_attributes.gemspec
@kbrock Please review. This should remove some of the Mend Bolt issues around rexml.
> Bump manageiq-style for rexml CVEs

- CHANGELOG.md
* Use TableAlias for table aliasing [#168](https://github.com/ManageIQ/activerecord-virtual_attributes/pull/168)
* Rails 7.1 support
> version 7.1 changelog

- activerecord-virtual_attributes.gemspec
Update manageiq-style to latest
> Update manageiq-style to latest

- lib/active_record/virtual_attributes.rb
- lib/active_record/virtual_attributes/virtual_delegates.rb
- lib/active_record/virtual_attributes/virtual_fields.rb
- spec/spec_helper.rb
minor changes
- fix syntax of class variables
- add rubocop exception for rails monkeypatch (it is rails code)
- reduce test coverage to only measure coverage of code and not of specs
> Minor tweaks to class vars and spec running modifications

- lib/active_record/virtual_attributes/virtual_arel.rb
- lib/active_record/virtual_attributes/virtual_delegates.rb
- lib/active_record/virtual_attributes/virtual_fields.rb
- lib/active_record/virtual_attributes/virtual_reflections.rb
- spec/db/models.rb
- spec/support/database.rb
- spec/virtual_attributes_spec.rb
- spec/virtual_delegates_spec.rb
Still have a bunch of rubocops in the spec due to the way we create the `TestClass`.
But this should resolve most other issues.
> fix rubocops

- lib/active_record/virtual_attributes.rb
- lib/active_record/virtual_attributes/virtual_delegates.rb
- spec/virtual_delegates_spec.rb
> use kwargs for virtual_column and virtual_delegate

- lib/active_record/virtual_attributes.rb
- lib/active_record/virtual_attributes/virtual_arel.rb
- lib/active_record/virtual_attributes/virtual_delegates.rb
- lib/active_record/virtual_attributes/virtual_includes.rb
- spec/db/models.rb
- spec/support/with_test_class.rb
- spec/virtual_attributes_spec.rb
- spec/virtual_delegates_spec.rb
@jrafanie this was the next step
Depends:
> Early includes and arel definition
