ManageIQ/activerecord-virtual_attributes

.travis.yml
Appraisals
Gemfile
gemfiles/virtual_attributes_50.gemfile
gemfiles/virtual_attributes_51.gemfile
lib/active_record/virtual_attributes/virtual_delegates.rb
lib/active_record/virtual_attributes/virtual_fields.rb
lib/active_record/virtual_attributes/virtual_total.rb

Move our rails 5.1 `virtual_attribute` changes from manageiq to here.
NOTE:
tested:
- `join_keys` change
- `aliases` => `_`
untested:
- `&block`
- `find_with_associations`
see also https://github.com/ManageIQ/manageiq/pull/18076

rails 5.1 support

---

activerecord-virtual_attributes.gemspec
lib/activerecord-virtual_attributes.rb

removing the underscore for consistency
with rails AR gem convention
prepping to rename repo over to `activerecord-virtual_attributes`

rename to activerecord_virtual_attributes

---

lib/active_record/virtual_attributes/virtual_fields.rb
spec/virtual_attributes_spec.rb

In rails 5.1, it was not properly aliasing the names of columns
after an `includes().references()`
The attributes were coming across as the alias name instead of the attribute name

 Fix includes(va).references(va) in rails 5.1

---

lib/active_record/virtual_attributes.rb

This PR adds support for the data types used by previous versions of this extension.f
Some parts of the app are throwing errors when deserializing yaml from the database:
```
ArgumentError: undefined class/module VirtualAttributes::Type::
```
This happens because a data type was stored in yaml. Those values have changed and the existing one can't be found anymore
/cc @mzazrivec This should solve your problem

Support legacy types for attributes

---

spec/support/match_query_limit_of.rb
spec/virtual_total_spec.rb

need these tests to address more edge cases
if you notice, the same attribute for the same models are returning different values depending upon what is preloaded.
This set of tests document the current behavior, so future code changes can make the behavior changes more obvious (as they work to getting the same values regardless of the loaded values)

Add tests for virtual totals

---

spec/db/models.rb
spec/support/match_query_limit_of.rb
spec/virtual_attributes_spec.rb
spec/virtual_total_spec.rb

- tests are more consistent for the null checks.
- tests around requires and includes
- replaced `not_raise_exception` with query expectations. so rather than just say "works", it now also ensures the correct data was fetched.
- `create_books` actually returns books to make a few specs easier to write
- fixed 'named_books' `:uses` clause. now `includes(:named_books)` actually does something (this was detected from the `not_raise_exception` change)

tests for null checks, requires and includes, and query expectations

---

lib/active_record/virtual_attributes/virtual_delegates.rb
spec/virtual_attributes_spec.rb

Alternate to #20 
Allow virtual delegate to be specified or discovered
For the most part, discovery works great.
Unfortunately it can cause a cascade of `load_schema` calls for the referenced classes.
This causes issues when we are doing a bunch of blanket field discovery calls.
This is related to:
- https://github.com/ManageIQ/manageiq-api/pull/416/files
- https://bugzilla.redhat.com/show_bug.cgi?id=1700378

Allow virtual delegate to be specified or discovered

---

lib/active_record/virtual_attributes/virtual_total.rb
spec/virtual_total_spec.rb

postgres does not allow a `COUNT(*)` to have an `ORDER BY` in the query.
This removes the `ORDER BY` from `COUNT(*)` queries. (all virtual_total queries are aggregate queries, so all of them do not want the order.)
NOTE: in mysql and sqlite, nulls sort before other value, but in postgres, they come later.
One of the tests sorted with a null and would fail in postgres. `author0` had no books.
I changed a test to not deal with this edge case.
Will deal with this when we get virtual aggregates fixed in #15

Remove COUNT(*) ORDER BY

---

lib/active_record/virtual_attributes/virtual_fields.rb
spec/db/models.rb
spec/db/schema.rb
spec/virtual_attributes_spec.rb
spec/virtual_includes_spec.rb

Fixes an issue when an includes references a column without using hashes.
invalid columns were silently failing in many cases.
Which is a problem because it was missing some includes.
This plugs that hole so we can properly fix these problems when we see them
```ruby
Author.includes(:books => [:author]).references(:books => {:author => {}}).map(&:name)
ActiveRecord::ConfigurationError:
nil
...
Author.includes(:books => [:author]).references(:books => {:author => {}}).to_a
["foo", "foo", "foo"]
```
Also
```ruby
Author.includes(:books => {:invalid => {}}).references(:books).map(&:name)
["foo", "foo", "foo"]
Author.includes(:books => {:invalid => {}}).references(:books).map(&:name)
ActiveRecord::ConfigurationError:
Can't join 'Author' to association named 'invalid'; perhaps you misspelled …
```

Fix poly references

---

spec/db/models.rb
spec/virtual_includes_spec.rb

Adding specs around a virtual attribute that uses another virtual attribute
this ensures that we recursively resolve the uses clauses

Test virtual using virtual attributes

---

lib/active_record/virtual_attributes/virtual_fields.rb
spec/virtual_attributes_spec.rb
spec/virtual_includes_spec.rb

the way `eager_loading` is handled changes over the rails versions.
It looks like virtual attributes only handles 5.0, and not quite up to snuff with 5.1 (or 5.2)
This brings the eager loading up to par.
This also fixes a bug dealing with includes() passing in array.
/cc @jrafanie this is the issue you were seeing with 5.1 migration

Support rails 5.1 for preloading values

---

lib/active_record/virtual_attributes/virtual_fields.rb
spec/virtual_attributes_spec.rb

properly quote virtual attribute names
Sometimes the attribute name is not sql friendly.
the will properly quote the attribute name
In our case, custom attributes sometimes have non sql friendly name for the virtual attribute. this escapes the code and makes us all happy
NOTE: this is the first commit from #27 -- I wanted that code to stick around so I created this smaller PR

quote column aliases

---

lib/active_record/virtual_attributes/virtual_fields.rb
spec/virtual_includes_spec.rb

if we use virtual attributes in outer joins, then translate the column
In MIQ, the turbo button uses `left_joins` instead of `references`
https://github.com/ManageIQ/manageiq/pull/18892
- `references`/`includes` properly translate virtual attributes  :+1:
- `left_joins` will not  :-1:
So when using the turbo button, reports blew up.
```
ActiveRecord::ConfigurationError:
Can't join 'ExtManagementSystem' to association named 'hostname'; perhaps you misspelled it?
```
- `references`/`includes` properly translate virtual attributes :+1:
- `left_joins` properly translate virtual attributes :+1:
turbo button works.

Add support for left outer joins (fix turbo button)

---

activerecord-virtual_attributes.gemspec
spec/support/byebug.rb

not happy having byebug as a development dependency
but it just became too hard to constantly add this and comment it out
Of Note: Despite what rubocop says, MiQ core includes the byebug gem

Support bye bug

---

bin/console
init.rb

the gem was renamed, but the new name was not added to `./bin/console`
This also now connects to an empty test database (as suggested by the bin/console file) so it can be tested and exercised in the console.
```
./bin/console
Traceback (most recent call last):
1: from ./bin/console:4:in `<main>'
./bin/console:4:in `require': cannot load such file -- virtual_attributes (LoadError)
```
```
./bin/console
>Author.create_with_books(5)
>Author.count
>Book.count
```

fix broken bin/console

---

lib/active_record/virtual_attributes/virtual_fields.rb
spec/virtual_includes_spec.rb

We have a performance regression on the VMs page (`VmOrTemplate.yaml`)
Sometimes the page loads objects great, and other times it does an N+1 on `disks`.
This is a subset of #34 
The issue stems around with the way we handle `includes()` to load the objects for the VMs page.
```ruby
class VmOrTemplate
belongs_to :hardware
virtual_delegate :allocated_disk_storage, :uses => {:hardware => :disks}
end
```
For our views, we generate `includes()` for all virtual columns and associated tables:
- `hardware.name` -- `includes(:hardware)`
- `allocated_disk_storage` -- `includes(:hardware => :disks)` /via `:uses`
```ruby
VmOrTemplate.includes(:hardware).includes(:hardware => :disks).each do |vm|
puts "#{vm.id} #{vm.hardware.name} #{vm.allocated_disk_storage)
end
```
The issue is when you merge the 2 …

virtual includes - better deep merge for attributes

---

lib/active_record/virtual_attributes/rspec/have_virtual_attribute.rb
spec/have_virtual_attribute_spec.rb

`type_for_attribute` expects a string (not a symbol) in Rails 5.1 and before.
It allows a string or a symbol in Rails 5.2 and above.
This updates the spec to work in both Rails 5.1 and 5.2
It also adds spec coverage for the matcher

type_for_attribute fix

---

lib/active_record/virtual_attributes/virtual_fields.rb
spec/virtual_attributes_spec.rb
spec/virtual_includes_spec.rb

Rails uses `references(table_names)`
and knows nothing about hashes or relations 
(nor has it ever known).
These tests fix that problem.

use references properly

---

lib/active_record/virtual_attributes.rb
lib/active_record/virtual_attributes/virtual_fields.rb

Class names change across different active record versions.
This adds case statements to handle these types of changes across active record 5.2 and 6.0
This is extracted out of #39

Version specific versions

---

lib/active_record/virtual_attributes/virtual_fields.rb

it is confusing to have version checks with < or >
making them consistent
followup to https://github.com/ManageIQ/activerecord-virtual_attributes/pull/44
pedantic PR for @jrafanie

make version checks consistently >

---

lib/active_record/virtual_attributes/virtual_fields.rb
spec/virtual_attributes_spec.rb

pulled out https://github.com/ManageIQ/activerecord-virtual_attributes/pull/39
Virtual attributes are converted to sql when calling `select(column_names)`
Virtual attributes are converted to sql when building the sql. This is the same place that regular virtual attributes are converted to sql.
This is more complicated than I would have liked.
The same code converts select clauses and group by clauses.
While the select clause needs to have aliases, the grouping does not. So extra attributes were passed into the method to distinguish between the 2 use cases

Change select to work better with ActiveRecord 5.2/6.0

---

lib/active_record/virtual_attributes/virtual_fields.rb
lib/active_record/virtual_attributes/virtual_total.rb
spec/virtual_includes_spec.rb
spec/virtual_total_spec.rb

In code, mark this monkey patch as an pre ActiveRecord 5.0 only patch.
1. Make the version of active record that we are patching more explicit
2. Add tests to properly test this code.
3. Remove code that does the same conversion twice

Put version check around calculate monkey patch

---

spec/have_virtual_attribute_spec.rb
spec/spec_helper.rb
spec/support/with_test_class.rb
spec/virtual_attributes_spec.rb
spec/virtual_delegates_spec.rb
spec/virtual_includes_spec.rb
spec/virtual_total_spec.rb

minor change but does not fill global namespace with a bunch of methods.
Trying to get rid of a `./bin/console` warning:
```
irb: warn: can't alias context from irb_context.
```
google suggested this change. While it did not solve the problem, it looked like a good idea anyway. So still putting this PR in.

Disable global rspec monkey patching

---

lib/active_record/virtual_attributes/virtual_fields.rb

Depends:
Now that the merge works more inclusively, many of these `case` statements are no longer necessary

refactor use of deep_merge

---

lib/active_record/virtual_attributes/virtual_total.rb

This fixes Code Climate issues:
```
Method define_virtual_aggregate_method has a Cognitive Complexity of 20
(exceeds 11 allowed). Consider refactoring. 
```
- This makes no functional changes.
- It splits a method into 3 methods - to appease CodeClimate and me.
- added virtual_aggregate :size method to handle cases where someone used `virtual_aggregates` instead of `virtual_totals` (not sure if we should support this, but put in just in case)
viewing with `ignoring whitespace` makes it a little more obvious that stuff is just moved around

refactor: simplify virtual_aggregate and virtual_total

---

lib/active_record/virtual_attributes/virtual_total.rb
spec/virtual_total_spec.rb

There are a number of places in miq where using a `virtual_total` would simplify our code base. But those spots required that `virtual_total` works with `has_many :through`
This adds support for a `virtual_total` with a relation that uses one or more `:through => model`.
manually construct the arel for `virtual_total` attributes.
This required that we know a lot about scopes, `join_keys`, and other edge cases.
We also were not able to handle the edge case of having `:through => :model`
Let Active Record construct the arel for `virtual_total` attributes. We then tweak the arel by remove the primary table from the sub query since the table is already in our primary query.
We now support any relation that rails supports, since we are letting rails do the work for us

Rewrite virtual_total attribute_arel

---

spec/match_query_limit_of_spec.rb
spec/preload_values_spec.rb
spec/support/match_query_limit_of.rb

goal: improve test coverage to make [code climate](https://codeclimate.com/github/ManageIQ/activerecord-virtual_attributes/code?sort=test_coverage) even happier.
in the process, improved the failure message.

Add tests for match_query_limit_of

---

.travis.yml
lib/active_record/virtual_attributes/virtual_fields.rb
lib/active_record/virtual_attributes/virtual_total.rb

find_with_associations is only available for 5.1
virtual_arel with the `to_sql` is new from the `:through` fix. but easy enough to fix

Rails 52 includes

---

lib/active_record/virtual_attributes/rspec/have_virtual_attribute.rb
spec/match_query_limit_of_spec.rb
spec/support/match_query_limit_of.rb
spec/support/preload_values.rb

Matchers need `failure_message_when_negated` or `description`. Not both.
They read just a little better when both `failure_message`s are defined.
To be honest, removing `description` to increase code coverage in
code climate.

Remove description from matchers

---

.travis.yml
lib/active_record/virtual_attributes/virtual_fields.rb
spec/virtual_includes_spec.rb

Depends upon:
---
- When you specify a `from()` clause, rails 5.x stops using `arel_column` and basically breaks virtual attributes. Rails 6.0 works though, so monkey patching 5.{1,2} from rails 6.0.
- Virtual attributes in `select()` are embedded as sub-queries. These need to be accessed in `attributes[]`, and we use an alias for this.
- updates the associations in preload and then lets the standard preload logic work in a standard way
- preloading polymorphic in includes is no longer working. doesnt work in rails either, but we had it working for a little while

Support Rails 6.0 polymorphic associations

---

lib/active_record/virtual_attributes/virtual_fields.rb
spec/virtual_attributes_spec.rb

code climate is saying the code complexity is 14 (exceeds 11 allowed)
simply pulling out code into another method
removing a few RuboCop overrides that are no longer necessary after this change

separate instantiate with monkey patch to simplify

---

.travis.yml
lib/active_record/virtual_attributes/virtual_fields.rb
spec/virtual_includes_spec.rb

Support for rails 5.2
Basically 5.2 is the same as 6.0
6.0 did add a `polymorphic_parent` parameter that is passed around a lot (not quite as many places as I wanted). This parameter allows rails to detect if an invalid reference is passed into `preload()`.
While 5.2 does just eats those errors, it ended up being easier to just add support for that in 5.2 than implement a completely different solution, just with that one parameter gone.
I copied across `preloaders_on` for 5.2. It is basically the same for rails 5.2 and 6.0, but again, the extra parameter made leaving this out a pain - so it has been included.
The real change was with `preloaders_for_reflection`
5.2 does not have that method, but it does have the inlined code in `preloaders_for_one`.
Rails 6.0 and 5.2 handle the return …

Rails 52 support

---

lib/active_record/virtual_attributes/arel_groups.rb

We had a temporary patch for grouping while a pr was merged
It has been incorporated in rails 6.0, so updating the patch
to let us know this and when we can delete it
fixed in: https://github.com/rails/arel/pull/449
travis was not linking.
change: https://travis-ci.org/github/ManageIQ/activerecord-virtual_attributes/builds/669392260
since other are not running 6.0, no need for cross repo

Version check for grouping monkey patch

---

lib/active_record/virtual_attributes/virtual_arel.rb
spec/db/models.rb
spec/virtual_attributes_spec.rb
spec/virtual_total_spec.rb

Rails is now calling:
```
attribute = arel_attribute()
attribute.name
```
All of our `arel_attributes` return a grouping or an attribute
This change allows our return values from `arel_attributes`
to respond to `grouping.name`, so serialization information can be looked
up in rails.
I looked into deferring the call to `arel_attributes` in rails, but this
requires a change in the attribute handlers, which has been an exposed
interface for a while, so it is not possible.
I'm leaving as monkey patch stage.
We may want to look into getting closer to the attribute code
Not thrilled with this solution.
Can't subclass Grouping because class is hardcoded.
Can't subclass Attribute for same reason.
introduced by https://github.com/rails/rails/pull/32981
cross repo: …

work around attribute.name [5.2, 6.0]

---

lib/active_record/virtual_attributes/virtual_fields.rb
spec/virtual_includes_spec.rb

in 5.2, when we preload some values and the association has no record
then there will be a null in the preloaded values
if you call preloaded on these records, that null will freak
NoMethodError:
undefined method `replace_virtual_fields' for NilClass:Class
ASIDE:
in miq, spec/models/metric/ci_mixin/rollup_spec.rb:70 was failing with the above failure as it tried to preload the ems and one of the hosts had no ems_cluster

fixed 5.2 double preload with a null record

---

spec/virtual_attributes_spec.rb

Rails 5.2 has a deprecation warning for this spec.
```
DEPRECATION WARNING:
Dangerous query method (method whose arguments are used as raw SQL)
called with non-attribute argument(s): :"lower column".
Non-attribute arguments will be disallowed in Rails 6.0.
This method should not be called with user-provided values,
such as request parameters or model attributes.
Known-safe values can be passed by wrapping them in Arel.sql().
```

fix spec to remove raw sql deprecation warning

---

lib/active_record/virtual_attributes/virtual_fields.rb
spec/virtual_includes_spec.rb

Display warnings for invalid attributes
before:
we were throwing errors, which is correct, but introducing this error checking causes
too many problems.
after:
The deprecation will give us time to fix the issues
in a more reasonable time period.

Display warnings for invalid attributes

---

lib/active_record/virtual_attributes.rb

The `virtual_column` method was sometimes called with a type instead of `:type =>`.
While this was never valid, it was prevalent enough to code a fix.
These have all been cleared up, and this PR officially drops support for the bad call.
we're dropping support because ruby 2.7 doesn't like
a hash and named keys right next to each other.
This removes the warning:
```
warning: Passing the keyword argument as the last hash parameter is deprecated
```
Fixes #70 
/cc @agrare https://github.com/ManageIQ/manageiq/issues/19678

no longer support invalid virtual_column calls

---

spec/virtual_attributes_spec.rb

add specs to ensure the various ways to define ordering work with virtual attributes

ensure various ordering option works

---

lib/active_record/virtual_attributes/virtual_total.rb

At this time, there is a different method virtual_total
that does count/size. this guard clause calls that other method for the user
We have changed all our code to use the proper `virtual_total` calls, hence we didn't get caught by this error. we are keeping this for safety reasons.

fix typo in virtual aggregate guard clause

---

lib/active_record/virtual_attributes/virtual_delegates.rb
spec/db/models.rb
spec/db/schema.rb
spec/virtual_delegates_spec.rb

Before:
virtual delegates does not include the `type` column when fetching associated models.
So if a model has a polymorphic relationship (e.g. points to either books or authors), it would bring back extra records(e.g. books with author ids or authors with book ids).
It is a little bit of an edge case, and that is why this bug was not found until now. But since all tables start with an id of 1, the overlap can happen all the time.
In this case, you have to delegate from the has one side to the belongs to, which is uncommon for us and was not even possible before nick added the `limit()` and `order()` fixes.
In the bz example, the has_one only brings back one record, and it brought back a record with an id from a different class. So the limit (has one limits to one) brought back the wrong …

Fix delegates to start respecting polymorphic associations 

---

lib/active_record/virtual_attributes/virtual_total.rb
spec/virtual_total_spec.rb

Depends:
`virtual_aggregate` allows us to define a `sum(column)` up front and assign it to a `virtual_attribute`.
This means we define a virtual attribute as an aggregate of a relation, without defining any ruby or sql.
So `Author.total_ratings` the same as `author.books.sum(:ratings)`
Calculating the sum of a column when there are no records is surprisingly not straight forward.
ActiveRecord and ruby treat the sum of no rows as 0. While SQL treats it as `null` (`nil` in ruby terms)
```ruby
author = Author.create
author.books.size # => 0
author.books.sum(:rating) # => 0
[].sum # => 0
```
```sql
SELECT sum(ratings) AS sum FROM authors;
sum
---
null
```
There are a few methods for calculating the sum from an association:
- a one off database query
- a relation that is loaded in memory
- an …

Zero when no associated records (fix sorting)

---

lib/active_record/virtual_attributes/virtual_total.rb
spec/db/models.rb
spec/virtual_total_spec.rb

blocked by:
adding `virtual_average`, `virtual_minimum`, `virtual_maximum` to the work started about a year ago that handles the nil/0 discrepancy where ActiveRecord/ruby treat the sum of no rows as 0 while SQL treats it as null

Introduce aggregate methods for average, min, max

---

.travis.yml

per https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration: `If you currently specify sudo: false in your .travis.yml, we recommend removing that configuration soon.`

remove sudo:false from .travis.yml

---

lib/active_record/virtual_attributes/virtual_fields.rb

the 0.77 rubocop release standardized some of the cop names
in order for this disable line to work, we probably want to rename to match
as a **completely irrelevant** note, the automation engine repo never re-enables these cops when we do this trick there: 
`# rubocop:disable Naming/MethodParameterName` never has a matching enable line on any of the three occurrences 
<sub><sup>136/365 = 0.3726</sub></sup>

rename AlignHash cop

---

activerecord-virtual_attributes.gemspec
lib/active_record/virtual_attributes/virtual_delegates.rb
lib/active_record/virtual_attributes/virtual_fields.rb
lib/active_record/virtual_attributes/virtual_total.rb
spec/virtual_attributes_spec.rb
spec/virtual_includes_spec.rb

Lots of comment changes.
Some deprecations of rails 5.1 behavior
A few quick hits that are needed for rails 6.1 support.
commits: 
- stop using join_keys 
- comments to understand what changed in the cod
- more drop rails 5.1 changes
- drop deprecation warnings when associations are invalid 
- allow more recent versions of db query matchers (dev only)
- remove unneeded Arel::Attribute.to_sql 
- alphabetize gemspec
- remove send(:include)

Rails 5.2 changes (many needed for 6.1 support)

---

lib/active_record/virtual_attributes/virtual_arel.rb
spec/db/models.rb
spec/virtual_attributes_spec.rb

There has always been an non-enforced rule that the arel generated for a virtual_attribute needs to be wrapped in parenthesis. In Arel, this is called "grouping" aka `Arel::Nodes::Grouping`
If the Arel returned from `virtual_attribute :arel => lambda {}` is not a `Grouping`, the virtual attribute will be silently ignored.
If the Arel returned from `virtual_attribute :arel => lambda {}` is not a `Grouping`, the node will be converted to a `Grouping`

Auto add grouping

---

CHANGELOG.md
README.md

[skip ci]
This makes it more clear up front, before installing, what version to pick.  The changelog now references the README for the details.

Move versioning verbiage into README

---

.github/workflows/ci.yaml

Clean up the GHA workflow to be consistent with other repos
- Inline the options
- ports after options
- Move CC_TEST_REPORTER_ID to global env

Cleanup for consistency

---

lib/active_record/virtual_attributes/virtual_arel.rb
spec/db/models.rb
spec/virtual_attributes_spec.rb

6.1 introduced `HomogeneousIn`, an optimization for the `In` clause.
This introduced changes to `Attribute` that required our attention.
An attribute now needs to have a `name`, and be able to type cast parameters for the
datatype.
This change gives the virtual attribute more information for type casting.
Put in a PR for rails to hopefully remove our requirement to monkey patch
that operator. https://github.com/rails/rails/pull/45642

Fix virtual attributes and IN clauses

---

spec/db/models.rb

We used to just derive the types for virtual_delegates from the target attribute.
This rarely caused deadlocks from a race conditions in the class loader.
We removed all uses of this feature.
I am removing this from the test cases.
Still left the code that derives the type, but it is discouraged.

Add type for virtual_delegate tests

---

lib/active_record/virtual_attributes/virtual_arel.rb

We used to support multiple rails versions in the same branch.
Now we are using different branches per rails version.
So there is no need to have a version check

remove rails 61 version check

---

.github/workflows/ci.yaml

I noticed that we were still testing 2.7
Adding 3.1 support
Nothing happened to make me think this will break, but wanted to put putting this in place.
remember: We are linking our version to active record version numbers, so this branch (master is rails 6.1.x specific

add ruby 3.1 to test matrix

---

activerecord-virtual_attributes.gemspec
bin/setup
spec/preload_values_spec.rb
spec/spec_helper.rb
spec/virtual_attributes_spec.rb
spec/virtual_delegates_spec.rb
spec/virtual_includes_spec.rb
spec/virtual_total_spec.rb

We would like to clean up all records created in each test.
This was not properly working before so we had to manually delete records ourselves.
Rails ActiveRecord does provide `transactional_features` for tests, but it is not
so simple to implement. This functionality is provided by `rspec-rails`, but not
in standard `rspec` (which we are using).
Using DatabaseCleaner gem to clean up after each test.
The `transaction` strategy should work for us since we only use a single database
and a single connection.

Use database_cleaner to clear out tables

---

lib/active_record/virtual_attributes/virtual_delegates.rb
spec/db/models.rb
spec/db/schema.rb
spec/virtual_delegates_spec.rb

We were not properly escaping the arel in the association de-reference.
This use case is very particular and will only happen with hard coded strings in associations.
13016ba214dbfd98 rewrote to_sql to wrap in unprepared_statement in one spot but not in this spot. So I guess this continued that effort.
a53d9597d4550345 stated there was a problem but had no reproducer This added specs, but they don't look like they would be able to detect the mentioned issue. So I guess this continued that effort as well.

support bind variables in virtual delegate reflections

---

lib/active_record/virtual_attributes/virtual_delegates.rb
lib/active_record/virtual_attributes/virtual_total.rb
spec/db/models.rb
spec/db/schema.rb
spec/virtual_delegates_spec.rb

Depends:
It was necessary for years to convert the virtual attributes over to sql to remove
bind variables.
Since we have successfully added tests around habtm, `has_many :through`, and
relations with string types, it feels our coverage is good enough to trust them
around bind variables.
This removes some string processing / objects created, but more importantly, gets us away from calling `Arel.sql(arel.to_sql)` and just passing `arel`.
WIP: would like to merge a few of these other PRs and run miq cross test suite against this.
currently, I'm leaning towards merging this

Arel with binds

---

lib/active_record/virtual_attributes/virtual_total.rb
spec/db/models.rb
spec/virtual_total_spec.rb

We rewrote virtual_totals to leverage the sql generated by rails: https://github.com/ManageIQ/activerecord-virtual_attributes/pull/52
This was to support `has_many :through`, but it also supports habtm

Support virtual_totals for habtm

---

.github/workflows/ci.yaml
README.md
bin/setup
spec/db/database.yml
spec/spec_helper.rb
spec/support/database.rb

- Change bin/setup to do a "create if exists" for postgres
- Change bin/setup to not be overly verbose
- Change the DB env var to match the adapter name
- Isolate DB env var logic to the Database.adapter method
- Keep short-form adapter names for convenience
@kbrock Please review.  Just some small refactorings and cleanups that I pulled out of #125 .

Cleanup setup

---

lib/active_record/virtual_attributes/virtual_fields.rb
spec/db/models.rb
spec/virtual_includes_spec.rb

The use case that triggered this had more layers of indirection.
But the jist is when we map a `:uses` with an array, and one of the entries has a complex `:uses`,
it will end up with a nested hash.
```
virtual_has_many :field1, :uses => {:a => :b}
virtual_has_many :field2, :uses => :c
virtual_has_many :field3, :uses => [:field1, :field2]
```
```
references([:field3])
=>
references([:field1, :field2])
=>
references([{:a => :b}, :c]
```
And when we map that into a hash we end up with
```
{{:a => :b} => {}, :c => {}}
```
where `{:a => :b}` is a key pointing to an empty hash (i.e.: `{}`)
```
Issue with `Vm#used_storage`:
ERROR -- evm: [NoMethodError]: undefined method `to_sym' for {:hardware=>:disks}:Hash
Did you mean?  to_s
to_set
ERROR -- evm: …
```

Handle 'uses' delegating to another 'uses' that has a deep hash

---

lib/active_record/virtual_attributes/virtual_delegates.rb
lib/active_record/virtual_attributes/virtual_fields.rb
spec/virtual_includes_spec.rb

Clean up the symbol usage in the includes.
This contains 2 commits:
1. `virtual_delegates` now defines a symbolic `:uses` clause and generates a symbolic `includes` value for delegates that use the dot form(i.e.: `:to => "association.method"`)
2. `virtual_attribute :name, :uses => "table"` generates a symbolic `includes` (e.g.: `:table`)
Of note, this is not totally necessary.
- `ActiveRecord` seems to be ok with strings and symbols.
- `ActiveRecord` is also ok with duplicates (e.g.: `[:table, :table, "table"]`)
We currently still generate hashes and keys (e.g.: `[:table, {:table => :table2}]`). While I wish it were more clean, `ActiveRecord` is perfectly ok with this, too.

Symbol includes

---

CHANGELOG.md
lib/active_record/virtual_attributes/version.rb

Reminder: this is not semver. this needs to be version 6.1.x since this is to support rails 6.1.x
This feels low risk.
---
* Fix bind variables for joins with static strings #124
* Add `virtual_total` for `habtm` #123
* Fix: `:uses` clause now works with an array and nested hashes. #120
* Uses symbols in the `includes()` clause. defined by `virtual_attribute :uses` and virtual_delegate. #128

Version 6.1.2 notes

---

Gemfile
spec/virtual_attributes_spec.rb

Additionally, once sqlite3 is downgraded, the latest json 2.7.2 causes issues where OpenStruct is not defined, which worked with json 2.7.1. Only the specs use OpenStruct, so we should explicitly require it.
@kbrock Please review.  This should get master back to green.

Fix issue where sqlite3 2.x doesn't want to load with activerecord 6.1

---

activerecord-virtual_attributes.gemspec
lib/active_record/virtual_attributes/virtual_fields.rb

These were extracted from https://github.com/ManageIQ/activerecord-virtual_attributes/pull/133
* Allow rails 7 in gemspec
* Use new location for grouped_records in rails 7, add our patches to it
* Remove rails 6.0 and lower code
Additionally, I added warnings if the expected class is missing instance methods for the different versions of rails.  That way, if we try to prepend methods in future versions, we'll know if they were renamed or removed.
💚 [Cross repo](https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/873)

Rails 7 mvp (just get it runnable with rails 7)

---

lib/active_record/virtual_attributes/virtual_total.rb

We went from virtual_aggregate :sum to virtual_sum years ago. (5.0 time frame?)
extracted from #151 
removed in https://github.com/ManageIQ/manageiq/pull/20572

drop virtual_aggregate

---

activerecord-virtual_attributes.gemspec
bin/console
lib/active_record/virtual_attributes/rspec/have_virtual_attribute.rb
lib/active_record/virtual_attributes/virtual_delegates.rb
lib/active_record/virtual_attributes/virtual_fields.rb
lib/active_record/virtual_attributes/virtual_reflections.rb
lib/active_record/virtual_attributes/virtual_total.rb
seed.rb
spec/support/byebug.rb
spec/support/database.rb
spec/support/with_test_class.rb
spec/virtual_attributes_spec.rb
spec/virtual_delegates_spec.rb
spec/virtual_includes_spec.rb
spec/virtual_total_spec.rb

Now may be a good time to push these - as we will be ramping up our testing
None of these overlap with the active record 7.0 changes
I skipped a number of warnings around parenthesis. I felt they assisted the code. Also avoided changing the variable `to`, as with delegation, that is the correct phrase.
```
< 32 files inspected, 87 offenses detected, 58 offenses autocorrectable
---
33 files inspected, 51 offenses detected, 27 offenses autocorrectable
```

Resolve rubocops

---

lib/active_record/virtual_attributes.rb

extracted from #150 
in f53272a9 we removed 5.1 support, so no longer needed to override this method Should have deleted this method
I had expected some exclusion for virtual attributes, but stock has been working since 5.2, so letting it slide

Drop attributes_builder

---

lib/active_record/virtual_attributes/virtual_fields.rb
spec/virtual_attributes_spec.rb
spec/virtual_includes_spec.rb

`relace_virtual_field` sometimes returns unnecessary tiers of embedded hashes or arrays. E.g. `[[:field]]` instead of `:field`.
6.1 has one fixes, but is by no means exhaustive:
```ruby
association = association.first if association.kind_of?(Array) && association.size == 1
```
This fixes `replace_virtual_field` to not output that value. Since this is at the return of each level, it essentially applied recursively and flattens it significantly.
Added `freeze` in tests to verify that the input parameter is unmodified.

replace_virtual_field condenses returning includes

---

lib/active_record/virtual_attributes/virtual_arel.rb
lib/active_record/virtual_attributes/virtual_delegates.rb
lib/active_record/virtual_attributes/virtual_fields.rb
lib/active_record/virtual_attributes/virtual_total.rb

Virtual attributes need an attribute name. The node representing the attribute needs to return a name and type.
In order to work with `ToSql`, this needs to be in the `Arel::Nodes::` namespace.
- `Arel::Nodes::Grouping` was monkeypatched to return `name` and `relation`.
Reminder: This node represents the parenthesized grouping of sql.
- Remove monkey patch from `Arel::Nodes::Grouping`
- Introduce `Arel::Nodes::VirtualAttribute` that is basically a grouping
- `ToSql` treats this node as a `Grouping` (since that is the parent class)

Introduce Arel::Nodes::VirtualAttribute

---

.github/workflows/ci.yaml
CHANGELOG.md
Gemfile
activerecord-virtual_attributes.gemspec
lib/active_record/virtual_attributes/version.rb
lib/active_record/virtual_attributes/virtual_fields.rb
spec/spec_helper.rb
spec/virtual_includes_spec.rb

Fixed includes and select issues
we're good to go for rails 7.0 with this

Add rails 7.0 support and drop rails 6.1

---

lib/active_record/virtual_attributes/virtual_fields.rb

This is an optimization.
`klass_associations` needs to be an array.
It can be a `nil, symbol, Array` or `Hash`.
The `nil` case is handled by `blank?`.
The `Symbol` and `Hash` are converted to an `Array`
But the `Array` was being converted to a double `Array`.
Which was not horrible, but just calls a loader then another loader.
With this change, the loader only runs through the association once.

Don't run preloader on double arrays

---

bin/console
seed.rb

Goal
-----
Cut down on the clutter in the home directory
There is a `seed.rb` file, but it seems like overkill to keep this around.
Seed purpose
-------------
I run `bin/console` on sqlite to see the sql or how something runs. Every time going in there, I need to to seed data. The actual values don't matter, just that there is data.
I rarely use `postgres` and tend to use sqlite. The exception is when I'm trying to fix this `ORDER BY` but with `DISTINCT` columns - which only shows up for postgres and mysql databases.
Alternative solutions
------------
I did try moving seeding into `spec/supports`, but this gem loads the supports files before defining the models and connecting to the database.
In a perfect world, I could define seed data in the supports directory to be loaded when the …

move seed into bin/console

---

activerecord-virtual_attributes.gemspec

Goal
----
I just ran into issues with an exploded gem having a `.rubcop.yml` file.
Seems we shouldn't ship these.
So I removed unnecessary files.
Details
-------
Not sure what is classified as necessary.
- In the lists below, I lumped all `lib/*` files together to make it more readable.
- The `bin/*` files are for development. So I think they are not needed for distribution.
- Do we want to keep the `Rakefile` or `Gemfile`? Left in for now.
Before
------
[".codeclimate.yml",
".github/workflows/ci.yaml",
".gitignore",
".rspec",
".rubocop.yml",
".rubocop_cc.yml",
".rubocop_local.yml",
".whitesource",
".yamllint",
"CHANGELOG.md",
"Gemfile",
"LICENSE.txt",
"README.md",
"Rakefile",
"activerecord-virtual_attributes.gemspec",
"bin/console",
"bin/setup",
"init.rb",
"lib/*",
"renovate.json", …

Remove test files from packaged gem

---

spec/support/database.rb

Before
------
I like to put sql logging configuration in supports.
With this code here, I am not able to do that.
After
-----
No more setup code. I can now put my logging code of choice anywhere in `spec/support`

Remove sql logger setup from specs

---

spec/virtual_attributes_spec.rb

openstruct is no longer in the standard library
Could have gone with using `double()` but then it is just swapping one mock for another.
Since we only use it in a few spots, just removed it.

Drop openstruct

---

activerecord-virtual_attributes.gemspec

See core PR:
https://github.com/ManageIQ/manageiq/pull/23310

Pin concurrent-ruby to < 1.3.5 until we're on rails 7.1

---

.github/workflows/ci.yaml
Gemfile
lib/active_record/virtual_attributes/virtual_delegates.rb

* Support Rails 7.1 only on master
* Add ruby 3.2-3.4 to the test matrix, drop 2.7-3.0.
* Rails 7.1 removed the table_name alias to name so just use name:
See: https://www.github.com/rails/rails/pull/46864
* Rails 7.1 removed the writer for the table_alias so set the instance
variable.  Since they dropped the table_alias writer on the Arel::Table, we're
no longer modifying it so we can drop the dup.
See: https://www.github.com/rails/rails/pull/48927

Rails 7.1 support

---

spec/db/models.rb
spec/db/schema.rb
spec/virtual_delegates_spec.rb

I don't think we are testing joining a model to itself.
It feels contrived, so if you can think of a relationship that makes more sense, please share.

Add tests for delegations to same model

---

lib/active_record/virtual_attributes/virtual_delegates.rb
spec/db/models.rb
spec/support/with_test_class.rb
spec/virtual_attributes_spec.rb
spec/virtual_delegates_spec.rb

We used to derive the type for delegates.
But this causes our "Constant Problem" when loading the relation and reared it's head as random deadlocks.
No longer support this functionality
I had changed all references to declare the `:type` in the past, but a few have snuck back in. Will run cross repo and fix them before merging this one.
- https://github.com/ManageIQ/activerecord-virtual_attributes/pull/21
- #188

Require type for delegation

---

CHANGELOG.md
lib/active_record/virtual_attributes/version.rb
lib/active_record/virtual_attributes/virtual_fields.rb
spec/db/models.rb
spec/virtual_includes_spec.rb

When you `includes(:polymorphic => :attr)` and the `:attr` does not have a `:uses`,
this threw an exception.
Reason: Rails 7.2 added a `to_sym` in `reflect_on_association()`,
since `uses[:attr] = nil`, calling `reflect_on_association(nil)` had issues:
```
Failure/Error: reflection = record.class._reflect_on_association(association)
NoMethodError:
undefined method `to_sym' for nil
```
refs:
- https://github.com/rails/rails/issues/5172
- https://github.com/ManageIQ/manageiq-api/pull/1284
- https://github.com/ManageIQ/manageiq/issues/23518

Fix nil :uses issue when included through a polymorphic

---

lib/active_record/virtual_attributes.rb
lib/active_record/virtual_attributes/virtual_delegates.rb
spec/virtual_delegates_spec.rb
spec/virtual_includes_spec.rb
spec/virtual_total_spec.rb

- convert `expect().not_to verb` => `expect().not to verb` to keep the `to verb` together (i.e.: not split the infinitive)
- fix rubocops around spacing in blocks
- For :through declarations referencing unknown delegations, give a more descriptive error message
- remove duplicate bogus :through detection for virtual_delegates
currently mia: miq_bot and codeclimate.

spec wording, better error message for bogus va :through
